"""separa usuario inicio e fim na expedicao

Revision ID: 246589e040dc
Revises: 4b6689082a41
Create Date: 2026-08-17 13:33:06.370655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '246589e040dc'
down_revision: Union[str, Sequence[str], None] = '4b6689082a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expedicao_conferencias', sa.Column('usuario_inicio_id', sa.String(length=36), nullable=False))
    op.add_column('expedicao_conferencias', sa.Column('usuario_fim_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('expedicao_conferencias_ibfk_2'), 'expedicao_conferencias', type_='foreignkey')
    op.drop_index(op.f('ix_expedicao_conferencias_usuario_id'), table_name='expedicao_conferencias')
    op.create_index(op.f('ix_expedicao_conferencias_usuario_fim_id'), 'expedicao_conferencias', ['usuario_fim_id'], unique=False)
    op.create_index(op.f('ix_expedicao_conferencias_usuario_inicio_id'), 'expedicao_conferencias', ['usuario_inicio_id'], unique=False)
    op.create_foreign_key(None, 'expedicao_conferencias', 'usuarios', ['usuario_fim_id'], ['id'])
    op.create_foreign_key(None, 'expedicao_conferencias', 'usuarios', ['usuario_inicio_id'], ['id'])
    op.drop_column('expedicao_conferencias', 'usuario_id')
    op.add_column('expedicao_separacoes', sa.Column('usuario_inicio_id', sa.String(length=36), nullable=False))
    op.add_column('expedicao_separacoes', sa.Column('usuario_fim_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('expedicao_separacoes_ibfk_2'), 'expedicao_separacoes', type_='foreignkey')
    op.drop_index(op.f('ix_expedicao_separacoes_usuario_id'), table_name='expedicao_separacoes')
    op.create_index(op.f('ix_expedicao_separacoes_usuario_fim_id'), 'expedicao_separacoes', ['usuario_fim_id'], unique=False)
    op.create_index(op.f('ix_expedicao_separacoes_usuario_inicio_id'), 'expedicao_separacoes', ['usuario_inicio_id'], unique=False)
    op.create_foreign_key(None, 'expedicao_separacoes', 'usuarios', ['usuario_fim_id'], ['id'])
    op.create_foreign_key(None, 'expedicao_separacoes', 'usuarios', ['usuario_inicio_id'], ['id'])
    op.drop_column('expedicao_separacoes', 'usuario_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expedicao_separacoes', sa.Column('usuario_id', sa.String(length=36), nullable=False))
    op.drop_constraint(None, 'expedicao_separacoes', type_='foreignkey')
    op.drop_constraint(None, 'expedicao_separacoes', type_='foreignkey')
    op.create_foreign_key(op.f('expedicao_separacoes_ibfk_2'), 'expedicao_separacoes', 'usuarios', ['usuario_id'], ['id'])
    op.drop_index(op.f('ix_expedicao_separacoes_usuario_inicio_id'), table_name='expedicao_separacoes')
    op.drop_index(op.f('ix_expedicao_separacoes_usuario_fim_id'), table_name='expedicao_separacoes')
    op.create_index(op.f('ix_expedicao_separacoes_usuario_id'), 'expedicao_separacoes', ['usuario_id'], unique=False)
    op.drop_column('expedicao_separacoes', 'usuario_fim_id')
    op.drop_column('expedicao_separacoes', 'usuario_inicio_id')
    op.add_column('expedicao_conferencias', sa.Column('usuario_id', sa.String(length=36), nullable=False))
    op.drop_constraint(None, 'expedicao_conferencias', type_='foreignkey')
    op.drop_constraint(None, 'expedicao_conferencias', type_='foreignkey')
    op.create_foreign_key(op.f('expedicao_conferencias_ibfk_2'), 'expedicao_conferencias', 'usuarios', ['usuario_id'], ['id'])
    op.drop_index(op.f('ix_expedicao_conferencias_usuario_inicio_id'), table_name='expedicao_conferencias')
    op.drop_index(op.f('ix_expedicao_conferencias_usuario_fim_id'), table_name='expedicao_conferencias')
    op.create_index(op.f('ix_expedicao_conferencias_usuario_id'), 'expedicao_conferencias', ['usuario_id'], unique=False)
    op.drop_column('expedicao_conferencias', 'usuario_fim_id')
    op.drop_column('expedicao_conferencias', 'usuario_inicio_id')
    # ### end Alembic commands ###
