"""cria tabelas de expedicao (separacao e conferencia)

Revision ID: 4b6689082a41
Revises: 22c3528ed7ac
Create Date: 2026-08-17 13:30:27.240122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4b6689082a41'
down_revision: Union[str, Sequence[str], None] = '22c3528ed7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expedicao_conferencias',
    sa.Column('pedido_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expedicao_conferencias_pedido_id'), 'expedicao_conferencias', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_expedicao_conferencias_usuario_id'), 'expedicao_conferencias', ['usuario_id'], unique=False)
    op.create_table('expedicao_separacoes',
    sa.Column('pedido_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expedicao_separacoes_pedido_id'), 'expedicao_separacoes', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_expedicao_separacoes_usuario_id'), 'expedicao_separacoes', ['usuario_id'], unique=False)
    op.create_table('expedicao_conferencia_itens',
    sa.Column('conferencia_id', sa.String(length=36), nullable=False),
    sa.Column('pedido_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantidade_conferida', sa.Integer(), nullable=False),
    sa.Column('divergente', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conferencia_id'], ['expedicao_conferencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_item_id'], ['pedido_itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expedicao_conferencia_itens_conferencia_id'), 'expedicao_conferencia_itens', ['conferencia_id'], unique=False)
    op.create_index(op.f('ix_expedicao_conferencia_itens_pedido_item_id'), 'expedicao_conferencia_itens', ['pedido_item_id'], unique=False)
    op.create_table('expedicao_separacao_itens',
    sa.Column('separacao_id', sa.String(length=36), nullable=False),
    sa.Column('pedido_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantidade_separada', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_item_id'], ['pedido_itens.id'], ),
    sa.ForeignKeyConstraint(['separacao_id'], ['expedicao_separacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expedicao_separacao_itens_pedido_item_id'), 'expedicao_separacao_itens', ['pedido_item_id'], unique=False)
    op.create_index(op.f('ix_expedicao_separacao_itens_separacao_id'), 'expedicao_separacao_itens', ['separacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expedicao_separacao_itens_separacao_id'), table_name='expedicao_separacao_itens')
    op.drop_index(op.f('ix_expedicao_separacao_itens_pedido_item_id'), table_name='expedicao_separacao_itens')
    op.drop_table('expedicao_separacao_itens')
    op.drop_index(op.f('ix_expedicao_conferencia_itens_pedido_item_id'), table_name='expedicao_conferencia_itens')
    op.drop_index(op.f('ix_expedicao_conferencia_itens_conferencia_id'), table_name='expedicao_conferencia_itens')
    op.drop_table('expedicao_conferencia_itens')
    op.drop_index(op.f('ix_expedicao_separacoes_usuario_id'), table_name='expedicao_separacoes')
    op.drop_index(op.f('ix_expedicao_separacoes_pedido_id'), table_name='expedicao_separacoes')
    op.drop_table('expedicao_separacoes')
    op.drop_index(op.f('ix_expedicao_conferencias_usuario_id'), table_name='expedicao_conferencias')
    op.drop_index(op.f('ix_expedicao_conferencias_pedido_id'), table_name='expedicao_conferencias')
    op.drop_table('expedicao_conferencias')
    # ### end Alembic commands ###
