"""cria tabela marcas

Revision ID: 87bf647af8f4
Revises: 5c1e8f3a9d02
Create Date: 2026-08-17 12:36:10.384514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '87bf647af8f4'
down_revision: Union[str, Sequence[str], None] = '5c1e8f3a9d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcas_nome'), 'marcas', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marcas_nome'), table_name='marcas')
    op.drop_table('marcas')
    # ### end Alembic commands ###
