"""schema inicial

Revision ID: b9ee9602cf27
Revises: 
Create Date: 2026-06-21 17:41:30.416222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ee9602cf27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cnpj'), 'clientes', ['cnpj'], unique=True)
    op.create_table('produtos',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_codigo'), 'produtos', ['codigo'], unique=True)
    op.create_table('usuarios',
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('dispositivos',
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('ip_registro', sa.String(length=45), nullable=False),
    sa.Column('nome_amigavel', sa.String(length=120), nullable=False),
    sa.Column('contador_anomalias', sa.Integer(), nullable=False),
    sa.Column('confiavel', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispositivos_device_id'), 'dispositivos', ['device_id'], unique=False)
    op.create_index(op.f('ix_dispositivos_usuario_id'), 'dispositivos', ['usuario_id'], unique=False)
    op.create_table('orcamentos',
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('cliente_nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('cliente_cnpj', sa.String(length=18), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamentos_cliente_id'), 'orcamentos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_orcamentos_numero'), 'orcamentos', ['numero'], unique=True)
    op.create_table('usuario_permissoes',
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('dominio', sa.String(length=30), nullable=False),
    sa.Column('ler', sa.Boolean(), nullable=False),
    sa.Column('criar', sa.Boolean(), nullable=False),
    sa.Column('editar', sa.Boolean(), nullable=False),
    sa.Column('apagar', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'dominio', name='uq_usuario_dominio')
    )
    op.create_index(op.f('ix_usuario_permissoes_usuario_id'), 'usuario_permissoes', ['usuario_id'], unique=False)
    op.create_table('orcamento_itens',
    sa.Column('orcamento_id', sa.String(length=36), nullable=False),
    sa.Column('produto_id', sa.String(length=36), nullable=False),
    sa.Column('produto_codigo', sa.String(length=40), nullable=False),
    sa.Column('produto_descricao', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamento_itens_orcamento_id'), 'orcamento_itens', ['orcamento_id'], unique=False)
    op.create_index(op.f('ix_orcamento_itens_produto_id'), 'orcamento_itens', ['produto_id'], unique=False)
    op.create_table('sessoes',
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('dispositivo_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogada', sa.Boolean(), nullable=False),
    sa.Column('revogada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_uso_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('sync_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_dispositivo_id'), 'sessoes', ['dispositivo_id'], unique=False)
    op.create_index(op.f('ix_sessoes_refresh_token_hash'), 'sessoes', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_sessoes_usuario_id'), 'sessoes', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessoes_usuario_id'), table_name='sessoes')
    op.drop_index(op.f('ix_sessoes_refresh_token_hash'), table_name='sessoes')
    op.drop_index(op.f('ix_sessoes_dispositivo_id'), table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_index(op.f('ix_orcamento_itens_produto_id'), table_name='orcamento_itens')
    op.drop_index(op.f('ix_orcamento_itens_orcamento_id'), table_name='orcamento_itens')
    op.drop_table('orcamento_itens')
    op.drop_index(op.f('ix_usuario_permissoes_usuario_id'), table_name='usuario_permissoes')
    op.drop_table('usuario_permissoes')
    op.drop_index(op.f('ix_orcamentos_numero'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_cliente_id'), table_name='orcamentos')
    op.drop_table('orcamentos')
    op.drop_index(op.f('ix_dispositivos_usuario_id'), table_name='dispositivos')
    op.drop_index(op.f('ix_dispositivos_device_id'), table_name='dispositivos')
    op.drop_table('dispositivos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_produtos_codigo'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_clientes_cnpj'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
